// 此商品暫無照片 https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg
const menu = [
   {
    id: 2,
    title: "18S+21A+1624金球",
    chinese: "已上架 tsewv4pm",
    category: "HotPot",
    price: 531,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `筒香 周東 丸佳浩 濱口 高梨裕念 山崎颯 今永 大勢 大島 簽卡松井 中日一壘洋砲 源田 及川 伊藤將司 濱口 森友哉`,
    // 目前玩的
  },
  
  {
    id: 3,
    title: "13s+14a+136金球",
    chinese: "未上架 cdrxjhkz",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `岡本 湯淺 桑田 高橋周 石山 藤井 安樂 愛斗 加藤 宮城 高部 嘉弭真 中村`,
  },
  {
    id: 4,
    title: "14s+14a+126金球",
    chinese: "未上架 xvk6y73g",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `今永 松井 荒木 大島 岩崎 茶古*2 原樹理 源田 與座 萬波 上川佃 廣島洋將 高部英斗`,
  },
  {
    id: 5,
    title: "15s+16a+116金球",
    chinese: "未上架 c37u8qbw",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `源田 今永 筒香 上澤 石川步 茶古 山崎颯 清水 湯淺*2 野村 五十幡 包爾(大聯盟強投) 井上 茶古`,
  },
  
  {
    id: 6 ,
    title: "14S+16A+121金球",
    chinese: "未上架 32mtq5dw",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `宮城 松井 桑田 牧原大成 高梨雄平 大城 辰己 森協 伊勢 巨人隊洋投 西武洋投 包爾 近藤 大野雄大`,
  },
  {
    id: 7,
    title: "14S+14A+136金球",
    chinese: "未上架 bshxc785",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `戶鄉 松井 桑原 中村獎悟 原樹理 山崎颯 清水 湯淺 岡林 五十幡 高橋宏斗 山川 森下 安樂`,
  },
  {
    id: 8,
    title: "16S+16A+131金球",
    chinese: "未上架 e7twnbp6",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `坂本城志郎 soto 簽卡山田 周東 杉本 今永 田中 牧原大 戶鄉 長岡 伊勢 五十幡 高橋宏斗 村上 三森 養樂多洋投`,
  },
  {
    id: 9,
    title: "14S+14A+169金球",
    chinese: "未上架 qmv4h7xj",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `今宮 大島 戶鄉 湯淺 原樹理 高梨 清水 水上 大勢 藤川 簽卡松井 soto 小幡 中川皓太`,
  },
  {
    id: 10,
    title: "15s+20a+141金球",
    chinese: "未上架 a69z4drx",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `中村 源田 高橋宏斗 藤川 松井 藤井 福田 近本 泉(軟銀) 木澤 早川 牧秀悟 山崎伊 上川佃`,
  },
  {
    id: 11,
    title: "15S+17A+136金球",
    chinese: "未上架 e6natj7f",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `拓植 簽卡包爾 西純 高橋宏斗 湯淺 荒木 嘉渳真 島內 近藤大亮 加藤 石井 森下 野間 小川`,
  },
  
  {
    id: 12,
    title: "15S+16A+156金球",
    chinese: "未上架 cptn4h7m",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `近藤健介 山本 湯淺 宮城 高梨雄平 牧原大城*2 簽卡藤井 松本 原樹理 福田 板東 村上颂數 茶古 藤岡`,
  },
  {
    id: 13,
    title: "14S+18A+111金球",
    chinese: "未上架 pvc6wjqa",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `小幡 五十幡 大田 戶鄉 柳裕也 松井 桑田 安達 岩貞 簽卡藤井 近藤大亮 橫川凱 村林 廣島洋投`,
  },
  {
    id: 14,
    title: "13S+19A+141金球",
    chinese: "未上架 35yjfc6q",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `國家隊近藤健介 近藤健介*2 簽卡松井 松井 石原 和田毅 則本 岩貞 岩崎 清宮 與座 佐藤督志也`,
  },
  {
    id: 15,
    title: "15S+13A+149金球",
    chinese: "未上架 9fhmwj2q",
    category: "HotPot",
    price: 0,
    img: "https://greensupply.com.tw/file/user/product/594prodImg20180823033006_1.jpg",
    desc: `甲斐 五十幡 森友哉 藤川 大島 上澤 有原 今永 小笠原 西口 簽卡坂倉 秋原 泉 今永 茶古`,
  },
  // {
  //   id: 20,
  //   title: "Oysters 鮮蚵鍋",
  //   chinese: "鮮蚵鍋",
  //   category: "HotPot",
  //   price: 340,
  //   img: "./images/hotpot2.jpg",
  //   desc: `Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 21,
  //   title: "2-Kinds of Seafood 海鮮雙拼鍋",
  //   chinese: "海鮮雙拼鍋",
  //   category: "HotPot",
  //   price: 390,
  //   img: "./images/hotpot3.jpg",
  //   desc: `2-Kinds Of Seafood can choose Oysters,Clams, Shrimp, Fish Fillet.<br>Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 22,
  //   title: "Shrimp 鮮蝦鍋",
  //   chinese: "鮮蝦鍋",
  //   category: "HotPot",
  //   price: 340,
  //   img: "./images/hotpot5.jpg",
  //   desc: `Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 23,
  //   title: "Fish Fillet 魚片鍋",
  //   chinese: "魚片鍋",
  //   category: "HotPot",
  //   price: 340,
  //   img: "./images/41.jpg",
  //   desc: `Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 24,
  //   title: "3-Kinds of Seafood 三鮮鍋",
  //   chinese: "三鮮鍋",
  //   category: "HotPot",
  //   price: 390,
  //   img: "./images/42.jpg",
  //   desc: `3-Kinds Of Seafood can choose Oysters,Clams, Shrimp, Fish Fillet.<br>Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 25,
  //   title: "Oysters With Choice of Meat 鮮蚵肉片鍋",
  //   chinese: "鮮蚵肉片鍋",
  //   category: "HotPot",
  //   price: 349,
  //   img: "./images/hotpot10.jpg",
  //   desc: `Can choose A or B. A is more meat ,B is more vegetables.<br>Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 26,
  //   title: "Fish Fillet with Choice of Meat 鮮魚肉片鍋",
  //   chinese: "鮮魚肉片鍋",
  //   category: "HotPot",
  //   price: 349,
  //   img: "./images/33.jpg",
  //   desc: `Can choose A or B. A is more meat ,B is more vegetables.<br>Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 27,
  //   title: "Shrimp with Choice of Meat 鮮蝦肉片鍋",
  //   chinese: "鮮蝦肉片鍋",
  //   category: "HotPot",
  //   price: 349,
  //   img: "./images/hotpot12.jpg",
  //   desc: `Can choose A or B. A is more meat ,B is more vegetables.<br>Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 28,
  //   title: "Clams with Choice of Meat 蛤蜊肉片鍋",
  //   chinese: "蛤蜊肉片鍋",
  //   category: "HotPot",
  //   price: 349,
  //   img: "./images/hotpot14.jpg",
  //   desc: `Can choose A or B. A is more meat ,B is more vegetables.<br>Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 29,
  //   title: "3-Kinds of Seafood with Choice of Meat 三鮮肉片鍋",
  //   chinese: "三鮮肉片鍋",
  //   category: "HotPot",
  //   price: 415,
  //   img: "./images/36.jpg",
  //   desc: `Can choose A or B. A is more meat ,B is more vegetables.<br>Not suitable for people allergic to seafood.`,
  // },
  
  
  
  
  
  // {
  //   id: 30,
  //   title: "Egg 蛋",
  //   chinese: "蛋",
  //   category: "sideMeal",
  //   price: 10,
  //   img: "./images/egg.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one.`,
  // },
  // {
  //   id: 31,
  //   title: "rice 飯",
  //   chinese: "飯",
  //   category: "sideMeal",
  //   price: 15,
  //   img: "./images/rice.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one.`,
  // },
  // {
  //   id: 32,
  //   title: "winter noodles 冬粉",
  //   chinese: "冬粉",
  //   category: "sideMeal",
  //   price: 15,
  //   img: "./images/1.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one.`,
  // },
  // {
  //   id: 33,
  //   title: "noodles 烏龍麵",
  //   chinese: "烏龍麵",
  //   category: "sideMeal",
  //   price: 15,
  //   img: "./images/1.png",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one.`,
  // },
  // {
  //   id: 34,
  //   title: "noodles oodles 王子麵",
  //   chinese: "王子麵",
  //   category: "sideMeal",
  //   price: 15,
  //   img: "./images/2.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one.`,
  // },
  // {
  //   id: 35,
  //   title: "Braised pork rice 魯肉飯",
  //   chinese: "魯肉飯",
  //   category: "sideMeal",
  //   price: 25,
  //   img: "./images/rice2.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one or +NT10 upgrade Braised pork rice.`,
  // },
  // {
  //   id: 36,
  //   title: "Spicy Braised pork rice 麻辣魯肉飯",
  //   chinese: "魯肉飯",
  //   category: "sideMeal",
  //   price: 30,
  //   img: "./images/rice2.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one or +NT10 upgrade Braised pork rice.`,
  // },
  // {
  //   id: 37,
  //   title: "Tossed Rice with Pork Lard 豬油拌飯",
  //   chinese: "豬油拌飯",
  //   category: "sideMeal",
  //   price: 25,
  //   img: "https://www.chientu.com.tw/upload/web/product/carte4.jpg",
  //   desc: `If you order a pot, you can choose to rice,egg,noodle,winter noodle,noodles oodles for one or +NT10 Tossed Rice with Pork Lard.`,
  // },
  // {
  //   id: 38,
  //   title: "Golden Shrimp Starch 金多蝦漿",
  //   chinese: "金多蝦漿",
  //   category: "else",
  //   price: 50,
  //   img: "./images/carte1.jpg",
  //   desc: `Not suitable for people allergic to seafood.`,
  // },
  // {
  //   id: 39,
  //   title: "Pig Blood Rice Cake 豬血糕",
  //   chinese: "豬血糕",
  //   category: "else",
  //   price: 30,
  //   img: "./images/carte3.jpg",
  //   desc: `Pig Blood Rice Cake.`,
  // },
  // {
  //   id: 40,
  //   title: "Taro 芋頭",
  //   chinese: "芋頭",
  //   category: "else",
  //   price: 45,
  //   img: "./images/taro.jpg",
  //   desc: `Taro is a tropical plant grown primarily for its edible corms.`,
  // },
  // {
  //   id: 41,
  //   title: "Fish Ball with Egg Stuffing 魚包蛋",
  //   chinese: "魚包蛋",
  //   category: "else",
  //   price: 60,
  //   img: "./images/123.jpg",
  //   desc: `Fish Ball with Egg Stuffing.`,
  // },
  // {
  //   id: 42,
  //   title: "Oily Chicken Platter 油雞",
  //   chinese: "油雞",
  //   category: "else",
  //   price: 160,
  //   img: "./images/recommend1.jpg",
  //   desc: `Oily Chicken Platter.`,
  // },
  // {
  //   id: 43,
  //   title: "Deep-Fried Pork Ribs 排骨酥",
  //   chinese: "排骨酥",
  //   category: "else",
  //   price: 60,
  //   img: "./images/recommend2.jpg",
  //   desc: `Deep-Fried Pork Ribs.`,
  // },
  // {
  //   id: 44,
  //   title: "Spicy Duck Blood 麻辣鴨血",
  //   chinese: "麻辣鴨血",
  //   category: "else",
  //   price: 40,
  //   img: "./images/recommend3.jpg",
  //   desc: `Hot and Spicy Duck Blood Jelly.`,
  // },
  // {
  //   id: 45,
  //   title: "Drunken Chicken Platter 醉雞盤",
  //   chinese: "醉雞盤",
  //   category: "else",
  //   price: 160,
  //   img: "./images/recommend4.jpg",
  //   desc: `Drunken Chicken Platter.`,
  // },
  // {
  //   id: 46,
  //   title: "Lobster Salad Ball 龍蝦沙拉丸",
  //   chinese: "龍蝦沙拉丸",
  //   category: "else",
  //   price: 40,
  //   img: "./images/recommend5.jpg",
  //   desc: `Lobster Salad Ball.`,
  // },
  

];
export default menu;